import { DictionaryEntry } from "../lib/radix-trie";

export const INITIAL_WORDS: DictionaryEntry[] = [
  { word: "abandon", meaning: "To leave somebody, especially somebody you are responsible for, with no intention of returning.", example: "The baby had been abandoned by its mother." },
  { word: "ability", meaning: "The fact that somebody/something is able to do something.", example: "The system has the ability to run more than one program at a time." },
  { word: "absence", meaning: "The state of being away from a place or a person.", example: "The decision was made in my absence." },
  { word: "absolute", meaning: "Total and complete.", example: "I have absolute confidence in her." },
  { word: "academic", meaning: "Connected with education, especially studying in schools and universities.", example: "The academic year begins in September." },
  { word: "accept", meaning: "To take willingly something that is offered.", example: "He asked me to marry him and I accepted." },
  { word: "access", meaning: "The opportunity or right to use something or to see somebody/something.", example: "Students must have access to a good library." },
  { word: "accident", meaning: "An unpleasant event that happens unexpectedly and causes injury or damage.", example: "He was killed in a car accident." },
  { word: "account", meaning: "An arrangement that somebody has with a bank to keep money there.", example: "I need to open a bank account." },
  { word: "accurate", meaning: "Correct and true in every detail.", example: "An accurate description of the event." },
  { word: "achieve", meaning: "To succeed in reaching a particular goal, status or standard.", example: "He finally achieved his ambition." },
  { word: "acquire", meaning: "To gain something by your own efforts, ability or behaviour.", example: "She has acquired a good knowledge of English." },
  { word: "action", meaning: "The process of doing something in order to make something happen.", example: "The time has come for action." },
  { word: "active", meaning: "Always busy doing things, especially physical activities.", example: "She's over 80 but is still very active." },
  { word: "actual", meaning: "Used to emphasize that something is real or exists in fact.", example: "The actual cost was higher than we expected." },
  { word: "adapt", meaning: "To change your behaviour in order to deal more successfully with a new situation.", example: "It's amazing how quickly people adapt." },
  { word: "addition", meaning: "The process of adding two or more numbers together to find their total.", example: "The addition of two and two is four." },
  { word: "address", meaning: "Details of where somebody lives or works and where letters can be sent.", example: "What's your new address?" },
  { word: "adequate", meaning: "Enough in quantity, or good enough in quality, for a particular purpose or need.", example: "The space available is not adequate for our needs." },
  { word: "adjust", meaning: "To change something slightly to make it more suitable for a new set of conditions.", example: "Watch out for the step—it's easy to trip if you don't adjust your stride." },
  { word: "admire", meaning: "To respect somebody for what they are or for what they have done.", example: "I really admire your enthusiasm." },
  { word: "admit", meaning: "To agree, often unwillingly, that something is true.", example: "It was a stupid thing to do, I admit." },
  { word: "adopt", meaning: "To take somebody else’s child into your family and become its legal parent(s).", example: "They have no children of their own, but they're hoping to adopt." },
  { word: "adult", meaning: "A fully grown person who is legally responsible for their actions.", example: "Children must be accompanied by an adult." },
  { word: "advance", meaning: "The forward movement of a group of people, especially an army.", example: "The enemy's advance was halted." },
  { word: "advice", meaning: "An opinion or a suggestion about what somebody should do in a particular situation.", example: "Let me give you a piece of advice." },
  { word: "afford", meaning: "To have enough money to be able to buy or do something.", example: "Can we afford a new car?" },
  { word: "afraid", meaning: "Feeling fear; frightened because you think that you might be hurt or that something bad might happen.", example: "Don't be afraid." },
  { word: "agency", meaning: "A business or an organization that provides a particular service especially on behalf of other businesses or organizations.", example: "An advertising agency." },
  { word: "agenda", meaning: "A list of items to be discussed at a meeting.", example: "What's on the agenda today?" },
  { word: "agent", meaning: "A person whose job is to act for, or manage the affairs of, other people in business, politics, etc.", example: "Our agent in New York." },
  { word: "agree", meaning: "To have the same opinion as somebody; to say that you have the same opinion.", example: "I agree with you." },
  { word: "ahead", meaning: "Further forward in space or time; in front.", example: "I'll go ahead and tell them you're coming." },
  { word: "alarm", meaning: "A loud noise or a signal that warns people of danger or of a problem.", example: "The fire alarm went off." },
  { word: "alcohol", meaning: "Drinks such as beer, wine, etc. that can make people drunk.", example: "He doesn't drink alcohol." },
  { word: "alive", meaning: "Living; not dead.", example: "Is your grandmother still alive?" },
  { word: "allow", meaning: "To let somebody do something; to let something happen or be done.", example: "His parents won't allow him to go out late." },
  { word: "almost", meaning: "Not quite; nearly.", example: "I've almost finished." },
  { word: "alone", meaning: "Without any other people.", example: "I like being alone." },
  { word: "along", meaning: "From one end to or towards the other end of something.", example: "We walked along the beach." },
  { word: "already", meaning: "Before now or before a particular time in the past.", example: "I've already seen that film." },
  { word: "alter", meaning: "To become different; to make somebody/something different.", example: "Prices did not alter significantly during 2014." },
  { word: "always", meaning: "At all times; on every occasion.", example: "I'll always love you." },
  { word: "amazing", meaning: "Very surprising, especially in a way that you admire.", example: "That's amazing!" },
  { word: "ambition", meaning: "Something that you very much want to do or achieve.", example: "His main ambition is to become a lawyer." },
  { word: "amount", meaning: "A sum of money or a quantity of something.", example: "The total amount was $100." },
  { word: "ancient", meaning: "Belonging to a period of history that is thousands of years in the past.", example: "Ancient Greece." },
  { word: "anger", meaning: "The strong feeling that you have when something has happened that you think is bad and unfair.", example: "He was filled with anger." },
  { word: "angle", meaning: "The space between two lines or surfaces that join, measured in degrees.", example: "A 90-degree angle." },
  { word: "animal", meaning: "A living creature that is not a bird, fish, insect or human.", example: "Wild animals." },
  { word: "announce", meaning: "To tell people something officially, especially about a decision, plans, etc.", example: "They announced their engagement." },
  { word: "annual", meaning: "Happening or done once every year.", example: "The annual general meeting." },
  { word: "another", meaning: "One more; a different person or thing.", example: "Would you like another drink?" },
  { word: "answer", meaning: "Something that you say, write or do to react to a question or situation.", example: "I'm still waiting for an answer." },
  { word: "anxiety", meaning: "The state of feeling nervous or worried that something bad is going to happen.", example: "Waiting for exam results is a time of great anxiety." },
  { word: "anybody", meaning: "Anyone.", example: "Is anybody there?" },
  { word: "anyway", meaning: "Used when adding something to support an idea or to say that something is true despite other things.", example: "It's too expensive and I don't like it anyway." },
  { word: "apart", meaning: "Separated by a distance, of space or time.", example: "The two houses are 500 metres apart." },
  { word: "appeal", meaning: "A deeply felt request for money, help or information that is needed immediately, especially one made by a charity or the police.", example: "The police made an appeal for witnesses." },
  { word: "appear", meaning: "To give the impression of being or doing something.", example: "He appeared to be tired." },
  { word: "apple", meaning: "A round fruit with red, yellow, or green skin and firm white flesh.", example: "She took a bite of the crisp red apple." },
  { word: "apply", meaning: "To make a formal request, usually in writing, for something such as a job, a place at college, university, etc.", example: "You should apply for the job." },
  { word: "appoint", meaning: "To choose somebody for a job or position of responsibility.", example: "They appointed him as manager." },
  { word: "area", meaning: "Part of a place, town, etc., or a region of a country or the world.", example: "The local area." },
  { word: "argue", meaning: "To speak angrily to somebody because you disagree with them.", example: "My brothers are always arguing." },
  { word: "arise", meaning: "To happen; to start to exist.", example: "A new difficulty has arisen." },
  { word: "army", meaning: "A large organized group of soldiers who are trained to fight on land.", example: "The British Army." },
  { word: "around", meaning: "On all sides of something; surrounding something.", example: "The earth moves around the sun." },
  { word: "arrange", meaning: "To plan or organize something in advance.", example: "I've arranged a meeting for Wednesday." },
  { word: "arrest", meaning: "If the police arrest somebody, the person is taken to a police station because the police think they have committed a crime.", example: "He was arrested for shoplifting." },
  { word: "arrival", meaning: "An act of coming or being brought to a place.", example: "The arrival of the train." },
  { word: "article", meaning: "A piece of writing about a particular subject in a newspaper or magazine, on a website, etc.", example: "Have you read this article?" },
  { word: "artist", meaning: "A person who creates works of art, especially paintings or drawings.", example: "A talented artist." },
  { word: "aside", meaning: "To one side; out of the way.", example: "He stepped aside to let me pass." },
  { word: "aspect", meaning: "A particular part or feature of a situation, an idea, a problem, etc.", example: "The financial aspect of the deal." },
  { word: "assist", meaning: "To help somebody to do something.", example: "We will assist you in any way we can." },
  { word: "assume", meaning: "To think or accept that something is true but without having proof of it.", example: "It is reasonable to assume (that) the economy will continue to improve." },
  { word: "attach", meaning: "To fasten or join one thing to another.", example: "I've attached a copy of the report." },
  { word: "attack", meaning: "An act of using violence to try to hurt or kill somebody.", example: "A brutal attack." },
  { word: "attempt", meaning: "An act of trying to do something, especially something difficult.", example: "Two people were killed in an attempt to climb the mountain." },
  { word: "attend", meaning: "To be present at an event, meeting, etc.", example: "How many people attended the meeting?" },
  { word: "attitude", meaning: "The way that you think and feel about somebody/something.", example: "A positive attitude." },
  { word: "attract", meaning: "If you are attracted by something, it interests you and makes you want it.", example: "I was attracted by the low price." },
  { word: "audience", meaning: "The group of people who have gathered to watch or listen to something.", example: "The audience applauded." },
  { word: "author", meaning: "A person who writes books, etc.", example: "Who is your favourite author?" },
  { word: "average", meaning: "Calculated by adding several amounts together, finding a total, and dividing the total by the number of amounts.", example: "The average age of the students is 20." },
  { word: "avoid", meaning: "To prevent something bad from happening.", example: "We must avoid another war." },
  { word: "award", meaning: "A prize such as money, etc. that is given to somebody who has been very successful.", example: "He won an award for best actor." },
  { word: "aware", meaning: "Knowing or realizing something.", example: "As far as I'm aware, nobody has complained." },
  { word: "away", meaning: "To or at a distance from a particular place, person or thing.", example: "Go away!" },
  { word: "baby", meaning: "A very young child or animal.", example: "A newborn baby." },
  { word: "back", meaning: "The part of the body that is on the opposite side to the chest.", example: "He lay on his back." },
  { word: "bad", meaning: "Unpleasant; full of problems.", example: "Bad news." },
  { word: "bag", meaning: "A container made of cloth, leather, plastic or paper, used for carrying things.", example: "A shopping bag." },
  { word: "bake", meaning: "To cook food in an oven without extra fat or liquid.", example: "I'm baking a cake." },
  { word: "balance", meaning: "A situation in which different things exist in equal, correct or good amounts.", example: "A healthy balance between work and play." },
  { word: "ball", meaning: "A round object used for throwing, hitting or kicking in games and sports.", example: "A tennis ball." },
  { word: "banana", meaning: "A long curved fruit with a thick yellow skin and soft flesh, that grows on a tropical tree.", example: "A bunch of bananas." },
  { word: "band", meaning: "A small group of musicians who play popular music together, such as rock, jazz, etc.", example: "A rock band." },
  { word: "bank", meaning: "An organization that provides various financial services, for example keeping or lending money.", example: "I need to go to the bank." }
];
